### ISSUE TITLE
New Admin Endpoints

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/analog-core#217]
High-level functionality

- [ ] Accounts / Update role https://github.com/AnalogIO/shifty-webapp/issues/6
- [ ] Accounts / Search for user (to be used by shifty)
- [ ] Purchases / Refund https://github.com/AnalogIO/shifty-webapp/issues/8
- [ ] Purchases / Issue Product https://github.com/AnalogIO/shifty-webapp/issues/5
- [x] Products / PUT, POST, DELETE https://github.com/AnalogIO/shifty-webapp/issues/7
- [ ] Statistics / Sum Unused Clips in given time period https://github.com/AnalogIO/shifty-webapp/issues/9

Suggested API design
```
POST api/v2/accounts/search
PATCH api/v2/accounts/{id}/user-group

POST api/v2/products
PUT api/v2/products/{id}
DELETE api/v2/products/{id}

POST api/v2/purchases/issue
PUT api/v2/purchases/{id}/refund

POST api/v2/statistics/unused-clips
```
