### ISSUE TITLE
Support new clip card types

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/analog-core#242]
## Context

From the start of the Spring 2024 semester, Analog will support new types of Clip Card products

- Three types of Clip Cards will be introduced
- Each type of clip card product can be used for one or more selected kinds of drinks. For example, Clip Card product 1 can be used for Cortado, Espresso and Clip Card product 2 can be used for Cafe Latte and Cocoa drinks
- No drink can be used for multiple clip card products
- To ensure that a barista does not have to verify that a clip card product is used for eligible drinks, the backend should verify that a ticket usage of a clip card product is used for eligible drinks too

### Classical Relational Database Approach

Tables

-  New table ProductEligbility with a composite key of ProductId and DrinkId. The table represents a mapping of what products are eligible for which drinks
- New table Drinks with columns representing information about a drink. 
- Change table Products to have a one-to-many property for ProductEligibility to represent what drink is eligible for
- Change table Tickets to introduce a new property which tracks what Drink a ticket has been used for

Comments

- Eligibility for a drink is verified by lookup in the ProductEligibiity table

## Tasks

- [ ] Add new API v2 endpoint for `POST tickets/use` which takes two properties, ProductId, DrinkId
- [ ] Add database changes
- [ ] Add new API v2 endpoint for `GET drinks` which lists all drinks
- [ ] Update Products API v2 endpoint `GET products` with new property to list all Drinks which a product is eligible for

![PXL_20240104_192155192](https://github.com/AnalogIO/analog-core/assets/25930103/c8dd07c6-a4dc-434e-a752-c8bdb121dfbe)

**Comment by jonasanker** [comment]
I'm very open to discussing the above suggestion :)

**Comment by jonasanker** [comment]
Cc @marfavi , @TTA777

**Comment by marfavi** [comment]
I'll write a comment on this tomorrow or Monday

**Comment by marfavi** [comment]
I haven't had proper time to suggest an alternative implementation due to exams, but I think the proposed solution is fine for our V2 API since it builds on our existing tables to have an implementation ready quickly. I'll have more time to look at this starting Friday :)
